apiVersion: v1
kind: Service
metadata:
  name: {{ include "portus-gateway.controllerServiceName" . }}
  labels:
    {{- include "portus-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.controller.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "portus-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
